name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run validation
      run: npm run validate
      
    - name: Check version sync
      run: node scripts/version.js info

  build:
    name: Build Extensions
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extensions
      run: npm run build
      
    - name: Upload Chrome build
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: .dist/monitor-sau-chrome.zip
        retention-days: 30
        
    - name: Upload Firefox build
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: .dist/monitor-sau-firefox.zip
        retention-days: 30

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Check for sensitive files
      run: |
        if find . -name "*.env*" -o -name "*secret*" -o -name "*key*" | grep -v node_modules | grep -v .git; then
          echo "❌ Sensitive files detected!"
          exit 1
        else
          echo "✅ No sensitive files found"
        fi

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [validate, build, security-scan]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extensions
      run: npm run build
      
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .dist/monitor-sau-chrome.zip
          .dist/monitor-sau-firefox.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}